
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [

    {
      type: 'category',
      label: 'Hercules',
      link: {
        type: 'generated-index',
        title: 'Hercules Architecture Decisions',
        description: 'Architecture decisions related to the Hercules configuration.',
        slug: '/hercules',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'hercules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Leo',
      link: {
        type: 'generated-index',
        title: 'Leo Architecture Decisions',
        description: 'Architecture decisions related to the Leo configuration.',
        slug: '/leo',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'leo',
        },
      ],
    },
    {
      type: 'category',
      label: 'Orion',
      link: {
        type: 'generated-index',
        title: 'Orion Architecture Decisions',
        description: 'Architecture decisions related to the Orion configuration.',
        slug: '/orion',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'orion',
        },
      ],
    },
  ],
};

module.exports = sidebars;
