/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  hercules_sidebar: [
    {
      type: "category",
      label: "Hercules Network ADR",
      link: {
        type: "generated-index",
        title: "Hercules Network Architecture Decisions",
        description: "Architecture decisions related to the Hercules network configuration.",
        slug: "/hercules_network"
      },
      items: [
        {
          type: "autogenerated",
          dirName: "hercules_network"
        }
      ]
    },
    {
      type: "category",
      label: "Hercules Use Case ADR",
      link: {
        type: "generated-index",
        title: "Hercules Use Case Architecture Decisions",
        description: "Architecture decisions related to the Hercules use case configuration.",
        slug: "/hercules_use_case"
      },
      items: [
        {
          type: "autogenerated",
          dirName: "hercules_use_case"
        }
      ]
    }
  ],

  leo_sidebar: [
    {
      type: 'category',
      label: 'Leo',
      link: {
        type: 'generated-index',
        title: 'Leo Architecture Decisions',
        description: 'Architecture decisions related to the Leo configuration.',
        slug: '/leo',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'leo',
        },
      ],
    },
  ],
  orion_sidebar: [
    {
      type: 'category',
      label: 'Orion',
      link: {
        type: 'generated-index',
        title: 'Orion Architecture Decisions',
        description: 'Architecture decisions related to the Orion configuration.',
        slug: '/orion',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'orion',
        },
      ],
    },
  ],
};

module.exports = sidebars;
